# Generated by Django 5.2.5 on 2026-02-24 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WATER', 'Water Supply'), ('ROAD', 'Road/Infrastructure'), ('ELECTRICITY', 'Electricity'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=20)),
                ('location_id', models.IntegerField()),
                ('location_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Reported to Higher Level'), ('SOLVED', 'Solved')], default='PENDING', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
